# Generated by Django 5.2.4 on 2025-07-13 14:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('editor', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='filenode',
            name='content',
            field=models.TextField(),
        ),
        migrations.AlterField(
            model_name='room',
            name='code',
            field=models.CharField(default='ccd7fd04', max_length=10, unique=True),
        ),
    ]
