# Generated by Django 5.2.4 on 2025-07-14 11:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('editor', '0004_room_creator_alter_room_code'),
    ]

    operations = [
        migrations.AlterField(
            model_name='room',
            name='code',
            field=models.CharField(default='d1bc8573', max_length=10, unique=True),
        ),
    ]
